include/libexfat.h

Fixes:
```c
../include/libexfat.h:72:1: error: unknown type name ‘ssize_t’
ssize_t exfat_read(int fd, void *buf, size_t size, off_t offset);
^
../include/libexfat.h:72:52: error: unknown type name ‘off_t’
ssize_t exfat_read(int fd, void *buf, size_t size, off_t offset);
^
../include/libexfat.h:73:1: error: unknown type name ‘ssize_t’
ssize_t exfat_write(int fd, void *buf, size_t size, off_t offset);
^
../include/libexfat.h:73:53: error: unknown type name ‘off_t’
ssize_t exfat_write(int fd, void *buf, size_t size, off_t offset);
^
../include/libexfat.h:75:1: error: unknown type name ‘ssize_t’
ssize_t exfat_utf16_enc(const char *in_str, __u16 *out_str, size_t out_size);
^
../include/libexfat.h:76:1: error: unknown type name ‘ssize_t’
ssize_t exfat_utf16_dec(const __u16 *in_str, size_t …
```

exfatprogs: add missing #include <sys/types.h>

---

lib/Makefile.am

Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

exfaprogs: add missing warning options in lib/Makefile.am

---

include/version.h

The major changes in this release:
* Rename project name to exfatprogs.
* label.exfat: Add support for label.exfat to set/get exfat volume label.
* Replace iconv library by standard C functions mbstowcs() and wcrtomb().
* Fix the build warnings/errors and add warning options.
* Fix several bugs(memory leak, wrong endian conversion, zero out beyond end of file) and cleanup codes
* Fix issues on big endian system and on 32bit system.
* Add support for Android build system.
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

exfatprogs: release 1.0.2 version

---

fsck/Makefile.am
mkfs/Makefile.am

There is some warning option which is reconized by only gcc version(gcc-9)
like -Wno-address-of-packed-member. To avoid the build break, remove it
and leave only -Wall.
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>

exfatprogs: remove -Werror to avoid build break

---

fsck/fsck.c

* Clang 9.0 incorrectly issues the -Wmissing-braces warning

fsck: Zero-init using memset

---

fsck/fsck.c
fsck/fsck.h
include/exfat_ondisk.h
mkfs/mkfs.c

Change cpu_to_le64()/cpu_to_le32()/cpu_to_le16() defines to
return determined types (instead of __le64/__le32/__le16) and
use PRIu64/PRIx64 to print 64-bit types.
Fixes:
mkfs.c:60:14: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Werror=format=]
exfat_debug("Volume Length(sectors) : %llu\n",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fsck.c:484:13: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Werror=format=]
exfat_err("too large sector count: %llu\n, expected: %llu\n",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fsck.c:851:13: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ …

mkfs/fsck: use PRIu64/PRIx64 to print 64-bit types (fixes issues #64)

---

fsck/fsck.c

The complicated way of gcc to tell not all failure pathes
set a return value != 0 in the calls before.
Fixes:
fsck.c:1063:18: error: ‘node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
node->parent = dir;
^
fsck.c:871:22: note: ‘node’ was declared here
struct exfat_inode *node;
^
Signed-off-by: Peter Seiderer <ps.report@gmx.net>

fsck: fix node may be used uninitialized (fixes issue #51)

---

mkfs/Makefile.am
mkfs/mkfs.c

The only use of the math library is in mkfs for log2(), which is easily
replaced by dividing the input number by 2 until it is reaches 1 or
less, and incrementing the output variable on each division, so remove
use of the math library.

mkfs: replace log2() with manual calculation

---

mkfs/mkfs.c
mkfs/mkfs.h

Rename DEFAULT_CLUSTER_SIZE macro to DEFAULT_BOUNDARY_ALIGNMENT.
If needed, we can add the option to adjust boundary alignment so that
writes to these areas will happen in as few flash blocks as possible.
Signed-off-by: Namjae Jeon <namjae.jeon@samsung.com>

mkfs: rename DEFAULT_CLUSTER_SIZE macro to DEFAULT_BOUNDARY_ALIGNMENT

---

Android.bp

* lseek() can only be used in this way when the overall size can
be represented in an off_t. Whenever this is called against
a block device of any reasonable size, it fails with EOVERFLOW.
* Member size in struct exfat_blk_dev is already an "unsigned long
long", guaranteed to be at least 64 bits, so lseek64() and off64_t
are a much more appropriate solution here.

libexfat: Don't die getting the size of non-miniature devices

---

README.md
include/libexfat.h
label/label.c
lib/libexfat.c
manpages/exfatlabel.8
manpages/tune.exfat.8
mkfs/mkfs.c
tune/tune.c

Add get/set volume serial option in exfatlabel and tune.exfat
$ sudo exfatlabel -i /dev/sdb1 0x1234
exfatprogs version : 1.0.4
New volume serial : 0x1234
$ sudo exfatlabel -i /dev/sdb1
exfatprogs version : 1.0.4
volume serial : 0x1234
Signed-off-by: Namjae Jeon <namjae.jeon@samsung.com>

exfatlabel: add get/set volume serial option

---

fsck/fsck.c
manpages/fsck.exfat.8

This is for backwards compatibility. It does the same as -p.
Signed-off-by: Matthieu CASTET <castet.matthieu@free.fr>

fsck: add -a option

---

include/libexfat.h
lib/libexfat.c
manpages/mkfs.exfat.8
mkfs/mkfs.c

This PR consists of three fixes and enhancements to `mkfs`, grouped into a single PR by [request](https://github.com/exfatprogs/exfatprogs/pull/142#issuecomment-774788255).
* **mkfs: avoid integer truncation when bounds checking cluster count** (formerly #143)
The bounds check on the number of data clusters in `mkfs.exfat` is subject to an integer truncation that would in most cases prevent the check from catching an out-of-bounds cluster count. This PR fixes the bounds check by moving the truncation to after the check.
Specifically: `finfo.total_clu_cnt` has type `unsigned int`, but `bd->size` has type `unsigned long long`, and the quotient resulting from the division may be wider than an `unsigned int`. Only the low bits of the quotient are compared against `EXFAT_MAX_NUM_CLUSTER`, but …

Three fixes and enhancements to mkfs

---

lib/libexfat.c

Eric found that bitmap data is not written normally in bitmap location
on s390x(64bit big endian system).
This patch make set_bit_le() etc 64-bit compatible, something like this
does seem to put the bits in the right place in the allocation bitmap at
mkfs time.
Signed-off-by: Eric Sandeen <sandeen@sandeen.net>
Signed-off-by: Namjae Jeon <namjae.jeon@samsung.com>

exfatprogs: libexfat: make set_bit_le() 64-bit compatible

---

NEWS
include/version.h

exfatprogs 1.1.1 - released 2021-04-21
======================================
CHANGES :
* mkfs.exfat: adjust the boundary alignment calculations to compensate
for the volume offset.
NEW FEATURES :
* mkfs.exfat: add the "--pack-bitmap" option to relocate the allocation
bitmap to allow the FAT and the bitmap to share the same allocation
unit on flash media.
BUG FIXES :
* Fix wrong bit operations on 64-bit big.
* Fix memory leaks in error paths.
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

exfatprogs: release 1.1.1 version

---

include/libexfat.h
label/label.c
lib/libexfat.c
tune/tune.c

This method won't ever use user input, so it's safe to
assume it'll never be required
As a bonus it fixes Android build
Signed-off-by: Luca Stefani <luca.stefani.ge1@gmail.com>

libexfat: Remove unused parameter in exfat_show_volume_serial

---

include/libexfat.h
label/label.c
lib/libexfat.c
tune/tune.c

- exfatprogs: tune: use sector size extracted from the boot sector
- exfatprogs: libexfat: fix wrong bd->num_sectors calculation

exfat-fixes

---

NEWS
include/version.h

exfatprogs 1.1.3 - released 2021-11-11
======================================
CHANGES :
* mkfs.exfat: ensure that the cluster size is greater than or
equal than the sector size.
* mkfs.exfat: replace lseek() + write() with pwrite().
BUG FIXES :
* mkfs.exfat: prevent an integer overflow when computing the FAT
length.
* fsck.exfat: fix a double free memory error.
Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

exfatprogs: release 1.1.3 version

---

manpages/exfatlabel.8

Update the synopsis to match the actual behaviour, the
serial_value must be provided after the device, like the
volume label_string. Also there is no lower case -v option,
change to upper case -V.
Rewrote the description slightly, and corrected some
lower/upper case mistakes along the way.
Signed-off-by: Sven Hoexter <sven@stormbind.net>

manpages: correct inaccuracies in the exfatlabel manpage

---

fsck/fsck.c

After recent fix there was an unnecessary extra if
statement and also the for loop contained needless
break statement.
Signed-off-by: Pavel Reichl <preichl@redhat.com>

fsck: Refactor bytes_to_human_readable()

---

NEWS
configure.ac
include/version.h
label/label.c
lib/libexfat.c
manpages/mkfs.exfat.8
mkfs/mkfs.c

Merge patches in exfat-next branch to master for 1.2.6 release
CHANGES :
* exfatprogs: replace obsolete autoconf and libtool
macros.
* mkfs.exfat: prefer the physical block size over
the logical block size for the exFAT sector size.
* mkfs.exfat: add notes about the format of the volume
GUID to the man page.
* mkfs.exfat: fix an incorrect calculation of the number
of used clusters.
BUG FIXES :
* exfatlabel: fix an user input error when setting
a volume serial or label.

Merge patches in exfat-next branch to master for 1.2.6 release
